<!--
/*
 * 注意 (2017-01-17)
 *
 * ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
 * 同時に修正されるファイル：
 *  - log_data/menu.inc
 *  - log_data/menu_resp.inc
 * ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
 */
-->

<div id="search">
<h2><img src="/images/header_search.gif" width="155" height="24" alt="商品検索"></h2>
<div id="searchin">
<FORM action="/goodssearch.php" method="GET">
<INPUT type="text" name="word" class="input01"><br>
<INPUT type="submit" value="検 索" class="button4">　<INPUT type="reset" class="button4">
</FORM>
</div>
</div>

<!-- カテゴリー -->
<div id="category01">
<h2><img src="/images/header_category.gif" width="155" height="24" alt="カテゴリー"></h2>
<ul>
	<li><a href="/" title="ＴＯＰ">ＴＯＰ</a></li>
	<li><a href="/goods/100/" title="バス">バス</a></li>
	<li><a href="/goods/200/" title="フライ">フライ</a></li>
	<li><a href="/goods/400/" title="トラウト">トラウト</a></li>
	<li><a href="/goods/500/" title="本・ビデオ">本・ビデオ</a></li>
	<li><a href="/goods/600/" title="衣類">衣類</a></li>
	<li><a href="/goods/800/" title="ソルト">ソルト</a></li>
	<li><a href="/goods/900/s903/" title="ハンドメイド">ハンドメイド</a></li>
	<li><a href="/goods/900/s904/" title="ステッカー・ワッペン">ステッカー・ワッペン</a></li>
	<li><a href="/goods/900/s908/" title="その他">その他</a></li>
	<li><a href="/goods/" title="全て">全て</a></li>
	<li><a href="/goods/category.htm" title="カテゴリー一覧">カテゴリー一覧</a></li>
	<li><a href="/goods/maker.htm" title="メーカー一覧">メーカー一覧</a></li>
</ul>
</div>
<div id="category02">
<ul>
	<li><a href="/tenpo/" title="店舗紹介">店舗紹介</a></li>
	<li><a href="/report/" title="釣行記">釣行記</a></li>
	<li><a href="/link/" title="リンク">リンク</a></li>
</ul>
</div>


<div id="category03">
<ul>
	<li><a href="/riyou/" title="ご利用案内">ご利用案内</a></li>
	<li><a href="/riyou/kaiketsu.htm" title="問題解決方法">問題解決方法</a></li>
	<li><a href="/tuhan.htm" title="通信販売法に基づく表記">通信販売法に基づく表記</a></li>
	<li><a href="/privacypolicy.htm" title="プライバシーポリシー">プライバシーポリシー</a></li>
	<li><a href="/inquiry.php" title="お問い合わせ">お問い合わせ</a></li>
</ul>

</div>

<div id="sougo_link" style="margin-top:100px;">
<h2>特別協賛相互リンク</h2>
     <ul>
          <li><a href="https://www.azet.jp/" target="_blank" title="eラーニングシステム制作 群馬県 有限会社アゼット">eラーニングシステム制作<br>群馬県 有限会社アゼット</a></li>
          <li><a href="https://uranairanking.jp/" target="_blank" title="星座占い ランキング">星座占い ランキング</a></li>
          <li><a href="https://www.futboljersey.com/" target="_blank" title="サッカーユニフォーム
サッカーシューズ
サッカーボール
フットサルシューズ
サッカー用品取扱サッカーショップ
ネイバーズスポーツ">サッカーユニフォームショップ<br>ネイバーズスポーツ</a></li>
     </ul>
</div>


<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-573797-2', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
