<?PHP
//	ヘッダ
function headmsg() {

	$html = <<<WAKABA
<img src="/image/header.jpg" width="800" height="110" border="0" alt="サッカーユニフォームやサッカースパイク・サッカーボールなどサッカー用品取り扱い/サッカー用品専門店 サッカーショップ ネイバーズスポーツ - NBS -" usemap="#head">
<map name="head">
  <area href="/" shape="rect" coords="640,0,800,27.5" alt="サッカー用品
サッカーユニフォーム
サッカースパイク
サッカーショップ
ネイバーズスポーツ
NBS">
  <area href="/1-SHOP/" shape="rect" coords="640,27.5,800,55" alt="店舗情報">
  <area href="/cago.php?mode=check" shape="rect" coords="640,55,800,82.5" alt="買物かご">
  <area href="mailto:query%40futboljersey.com?Subject=NBS%82%A8%96%E2%82%A2%8D%87%82%ED%82%B9" shape="rect" coords="640,82.5,800,110" alt="お問合せ">
  <area shape="default" nohref alt="サッカーユニフォームやサッカースパイク・サッカーボールなどサッカー用品取り扱い/サッカー用品専門店 サッカーショップ ネイバーズスポーツ - NBS -">
</map><br />
<br />

WAKABA;

	return $html;

}


//	<h1>セリエA、プレミアリーグ、スペインリーグ、各国代表等のチームユニフォームやスパイク・ボールなどサッカー用品取り扱い/サッカー用品専門店 サッカーショップ ネイバーズスポーツ</H1>

?>
