<?PHP
//	フッタ
function footmsg() {

	$html = <<<WAKABA
<a href="/" title="サッカー用品
サッカーユニフォーム
サッカースパイク
フットボールジャージドットコム
ネイバーズスポーツ" class="footer">サッカー用品
サッカーユニフォーム
サッカースパイク
フットボールジャージドットコム
ネイバーズスポーツ
NBS</a>
<!--
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-573797-1";
urchinTracker();
</script>
-->

WAKABA;

	return $html;

}
?>
