<!DOCTYPE html>
<HTML>
<HEAD>
	<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="initial-scale=1.0,width=device-width" />
	<META http-equiv="Content-Style-Type" content="text/css">
	<TITLE><!--TITLE--></TITLE>
	<!--SEO-KEYWORDS-->
	<!--SEO-DESCRIPTION-->
	<LINK rel="stylesheet" href="/sub/style.css" type="text/css">
	<meta http-equiv="Pragma" content="no-cache"> 
	<meta http-equiv="Cache-Control" content="no-cache">

	<!-- new CSS -->
	<link rel="stylesheet" href="/sub/responsive.css">
	<script src="/sub/jquery-3.1.0.min.js"></script>
	<script src="/sub/ozzys.js"></script>
</HEAD>

<BODY>
	<div class="page">
		<header>
			<div id="navigation-mobile"></div>

			<div class="stripes"></div>
			<div class="clearfix banner" style='background:black url(/images/<!--HEADIMG-->) top right no-repeat;'>
				<div class="logo">
					<a href="/"><img src="/images/ozzys-logo.gif" class="img-responsive" alt="ロゴ" width="190" height="136" border="0" /></a>
				</div>
				<div class="blockquote">
					<blockquote class="headmsg"><!--HEADMSG--></blockquote>
				</div>
			</div>

			<div id="navigation-pc">
				<nav id="navigation-header" class="clearfix" style="display: none">

					<div id="mobile-menu-overlay"></div>

					<div id="mobile-menu-left" class="mobile-menu">
						<div id="mobile-button-left" class="mobile-button" data-menu="left"></div>
						<div class="mobile-content">
							<div id="mobile-navbox"></div>
						</div>
					</div>

					<div id="mobile-menu-right" class="mobile-menu">
						<div id="mobile-button-right" class="mobile-button" data-menu="right">サイドを見る</div>
						<div class="mobile-content">
							<div id="mobile-col-right"></div>
						</div>
					</div>

					<!--LOGIN-->
				</nav>
			</div>
		</header>

		<div id="mobile-login-menu"></div>

		<div id="main">

			<!--======================================================================-->
			<!--left-->
			<!--======================================================================-->
			<div id="pc-col-left" class="col col-left stripes">
				<nav id="navbox">
					<!--MENU-->
				</nav> <!-- #navbox end -->
			</div> <!-- end .col-left -->


			<!--======================================================================-->
			<!--middle-->
			<!--======================================================================-->
			<div class="col col-middle">
				<!--MAIN-->
			</div> <!-- end .col-middle -->

			<!--======================================================================-->
			<!--right-->
			<!--======================================================================-->
			<div id="pc-col-right" class="col col-right">
				<div id="col-right">
					<!--OSUSUME-->
				</div> <!-- end #col-right -->
			</div> <!-- end .col-right -->

		</div> <!-- end #main -->

		<footer>
		</footer>
	</div> <!-- end .page -->

</BODY>
</HTML>
