#!/bin/bash

cp develop/www/images/btn-toparrow.png www/images/btn-toparrow.png
cp develop/www/images/mobile-menu-icon.png www/images/mobile-menu-icon.png
cp develop/www/images/ozzys-logo.gif www/images/ozzys-logo.gif
cp develop/www/log_data/menu_resp.inc www/log_data/menu_resp.inc
cp develop/www/loginmsg_resp.php www/loginmsg_resp.php
cp develop/www/maintenance.html www/maintenance.html
cp develop/www/menulist_resp.php www/menulist_resp.php
cp develop/www/osusume_resp.php www/osusume_resp.php
cp develop/www/oyasumi/1702oyasumi-l.jpg www/oyasumi/1702oyasumi-l.jpg
cp develop/www/oyasumi/1702oyasumi-s.jpg www/oyasumi/1702oyasumi-s.jpg
cp develop/www/pics-front/arrow_red_right5.gif www/pics-front/arrow_red_right5.gif
cp develop/www/pics-front/new.gif www/pics-front/new.gif
cp develop/www/sub/jquery.rwdImageMaps.min.js www/sub/jquery.rwdImageMaps.min.js
cp develop/www/sub/jquery-3.1.0.min.js www/sub/jquery-3.1.0.min.js
cp develop/www/sub/loginmsg_resp.inc www/sub/loginmsg_resp.inc
cp develop/www/sub/ozzys.js www/sub/ozzys.js
cp develop/www/sub/responsive.css www/sub/responsive.css
cp develop/www/sub/seo.class.php www/sub/seo.class.php
cp develop/www/whats_new-responsive-ssi.htm www/whats_new-responsive-ssi.htm
cp develop/www/cart.php www/cart.php
cp develop/www/conf.php www/conf.php
cp develop/www/endhtml/order1.htm www/endhtml/order1.htm
cp develop/www/endhtml/order2.htm www/endhtml/order2.htm
cp develop/www/endhtml/secession.htm www/endhtml/secession.htm
cp develop/www/endhtml/thank.htm www/endhtml/thank.htm
cp develop/www/endhtml/thank_hen.htm www/endhtml/thank_hen.htm
cp develop/www/endhtml/thank_inq.htm www/endhtml/thank_inq.htm
cp develop/www/endhtml/thank_pass.htm www/endhtml/thank_pass.htm
cp develop/www/goods.php www/goods.php
cp develop/www/goodssearch.php www/goodssearch.php
cp develop/www/index.htm www/index.htm
cp develop/www/inquiry.php www/inquiry.php
cp develop/www/link/index.htm www/link/index.htm
cp develop/www/log_data/menu.inc www/log_data/menu.inc
cp develop/www/log_data/news.inc www/log_data/news.inc
cp develop/www/login.php www/login.php
cp develop/www/loginmsg.php www/loginmsg.php
cp develop/www/member.php www/member.php
cp develop/www/menulist.php www/menulist.php
cp develop/www/phistory.php www/phistory.php
cp develop/www/privacypolicy.htm www/privacypolicy.htm
cp develop/www/riyou/index.htm www/riyou/index.htm
cp develop/www/riyou/kaiketsu.htm www/riyou/kaiketsu.htm
cp develop/www/riyou/mail.htm www/riyou/mail.htm
cp develop/www/riyou/payment.htm www/riyou/payment.htm
cp develop/www/secession.php www/secession.php
cp develop/www/sub/cart_new.inc www/sub/cart_new.inc
cp develop/www/sub/conf.inc www/sub/conf.inc
cp develop/www/sub/goodslist.inc www/sub/goodslist.inc
cp develop/www/sub/goodsname.inc www/sub/goodsname.inc
cp develop/www/sub/goodssearch.inc www/sub/goodssearch.inc
cp develop/www/sub/hinagata.inc www/sub/hinagata.inc
cp develop/www/sub/inquiry.inc www/sub/inquiry.inc
cp develop/www/sub/linktitle.inc www/sub/linktitle.inc
cp develop/www/sub/login.inc www/sub/login.inc
cp develop/www/sub/loginmsg.inc www/sub/loginmsg.inc
cp develop/www/sub/mainlist.inc www/sub/mainlist.inc
cp develop/www/sub/makerlist.inc www/sub/makerlist.inc
cp develop/www/sub/member.inc www/sub/member.inc
cp develop/www/sub/news.inc www/sub/news.inc
cp develop/www/sub/news_display.inc www/sub/news_display.inc
cp develop/www/sub/osusume.inc www/sub/osusume.inc
cp develop/www/sub/phistory.inc www/sub/phistory.inc
cp develop/www/sub/secession.inc www/sub/secession.inc
cp develop/www/sub/setup.inc www/sub/setup.inc
cp develop/www/sub/sublist.inc www/sub/sublist.inc
cp develop/www/sub/syousai.inc www/sub/syousai.inc
cp develop/www/sub/uresuji.inc www/sub/uresuji.inc
cp develop/www/tenpo/boat.htm www/tenpo/boat.htm
cp develop/www/tenpo/entra.htm www/tenpo/entra.htm
cp develop/www/tenpo/hlure1.htm www/tenpo/hlure1.htm
cp develop/www/tenpo/hlure2.htm www/tenpo/hlure2.htm
cp develop/www/tenpo/hlure3.htm www/tenpo/hlure3.htm
cp develop/www/tenpo/index.htm www/tenpo/index.htm
cp develop/www/tenpo/kousaku.htm www/tenpo/kousaku.htm
cp develop/www/tenpo/lure.htm www/tenpo/lure.htm
cp develop/www/tenpo/reeln.htm www/tenpo/reeln.htm
cp develop/www/tenpo/rodn.htm www/tenpo/rodn.htm
cp develop/www/tenpo/slure1.htm www/tenpo/slure1.htm
cp develop/www/tenpo/slure2.htm www/tenpo/slure2.htm
cp develop/www/tenpo/trout.htm www/tenpo/trout.htm
cp develop/www/tuhan.htm www/tuhan.htm
