<?PHP
//	鐃駿￥申鐃緒申HTML
//	鐃舜ッワ申
function head() {

	$html = <<<WAKABA
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title>鐃緒申鐃淑在庫醐申鐃緒申</title>
<style type="text/css">
<!--
body{
  font-size : 12px;
  margin-top : 0px;
  margin-left : 1px;
  margin-right : 0px;
  margin-bottom : 0px;
}
table{
  font-size : 12px;
}
.list_head{
  background-color : #cccccc;
}
.list_table{
  background-color : #666666;
}
.list_goods{
  background-color : #ffffff;
}
.list_goods2{
  background-color : #ffffcc;
}
-->
</style>
</head>
<body>

WAKABA;

	return $html;

}



//	鐃春ッワ申
function foot() {

	$html = <<<WAKABA
</body>
</html>

WAKABA;

	return $html;

}
?>
